#!/usr/bin/env python3
"""
make_treatment_configs.py — generate self-contained treatment configs on the
CURRENT base calibration.

Each output config = the base production template (S=1e4, dt=6h, E10x, v2
calibration) with a protocol-specific treatment block appended.  This keeps the
treatment runs consistent with the latest base production (params_S1e4_E10x_dt6h)
instead of the stale Jun-18 params_treat_*_S1e4.json (dt=30min, non-E10x, old
calibration).

Treatment parameters (Cioffi schedule, paper Section 5 / Fig. 5) are unchanged
from the validated Jun-18 configs — only the base body is refreshed.

Usage:
    python3 scripts/make_treatment_configs.py
    python3 scripts/make_treatment_configs.py --base configs/params_S1e4_E10x_dt6h.json
"""
import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# --- Treatment block (Cioffi schedule, paper Section 5) --------------------
# Shared across all drug protocols; flags select which drugs are active.
DRUG_BLOCK = {
    "treat_start_day": 14.0,     # paper day all treatments begin (sim day 7)
    "gem_gamma": 5.54,           # Gemcitabine decay (t1/2 ~ 3 h)
    "gem_dose": 0.1,             # calibrated: avg kill < tumor growth so C grows
                                 # during treatment (paper Fig.5); old 0.4 over-killed
    "gem_freq_days": 3.5,        # twice a week
    "gem_end_day": 56.0,
    "gem_c_c": 10.0,             # kill rate for C
    "gem_c_p": 7.5,              # kill rate for P
    "gem_c_immune": 1.8,         # kill rate for E, N, H, R
    "abr_gamma": 0.6161308,      # Abraxane decay (t1/2 ~ 1.1 d)
    "abr_dose": 0.015,           # calibrated (old 0.1 over-killed)
    "abr_freq_days": 4.0,        # every 4 days
    "abr_end_day": 28.0,
    "abr_c_c": 10.0,
    "abr_c_p": 10.0,
    "abr_c_immune": 6.4,
    "acd47_end_day": 35.0,
    "acd47_e_boost": 0.2,        # reproduces paper Fig.5a ~10x E spike in the ODE
                                 # (E rises during window then crashes). Old 0.05 too
                                 # weak; 0.15 gave ~4x; 0.2 gives ~10-12x (ODE). Higher
                                 # values further suppress C (E->C kill tension).
}

# Post-treatment reduced growth rate k_c, fitted per protocol in the paper
# (Fig. 5 subplot titles). Applied after the last treatment ends so each
# protocol reaches a DIFFERENT final tumor size (base k_c = 0.0887).
KC_POST_TREAT = {
    "acd47":     0.01899,
    "gem":       0.02545,
    "abr":       0.02517,
    "abr_acd47": 0.00276,
    "abr_csc":   0.02517,   # same as abr (CSC relapse handled separately)
}

# CSC block for the Fig. 6 relapse scenario (paper Section 6).
CSC_BLOCK = {
    "csc_enable": True,
    "S0": 10,
    "csc_a1": 0.35,
    "csc_a2": 0.65,
    "csc_a3": 0.0,
    "csc_lambda_max": 0.07,
    "csc_lambda_min": 0.001,
    "csc_delta_s": 0.0,
    "csc_sigma": 1000.0,
}

# --- Protocols: which flags/blocks each one turns on ------------------------
PROTOCOLS = {
    "untreated": {"flags": {"treat_gem": False, "treat_abr": False,
                            "treat_acd47": False}, "csc": False},
    "acd47":     {"flags": {"treat_gem": False, "treat_abr": False,
                            "treat_acd47": True},  "csc": False},
    "gem":       {"flags": {"treat_gem": True,  "treat_abr": False,
                            "treat_acd47": False}, "csc": False},
    "abr":       {"flags": {"treat_gem": False, "treat_abr": True,
                            "treat_acd47": False}, "csc": False},
    "abr_acd47": {"flags": {"treat_gem": False, "treat_abr": True,
                            "treat_acd47": True},  "csc": False},
    # CSC relapse (Section 6) — DISABLED: this model is Section 5 only.
    # "abr_csc":   {"flags": {"treat_gem": False, "treat_abr": True,
    #                         "treat_acd47": False}, "csc": True},
}


def build_config(base: dict, proto: str, spec: dict) -> dict:
    cfg = dict(base)
    cfg["_protocol"] = proto
    cfg["_note"] = (f"Treatment protocol '{proto}' on current base calibration "
                    "(S=1e4, dt=6h, E10x, v2). Generated by make_treatment_configs.py.")
    if proto != "untreated":
        cfg.update(DRUG_BLOCK)
        if proto in KC_POST_TREAT:
            cfg["kc_post_treat"] = KC_POST_TREAT[proto]
    cfg.update(spec["flags"])
    if spec["csc"]:
        cfg.update(CSC_BLOCK)
    return cfg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="configs/params_S1e4_E10x_dt6h.json",
                    help="Base production template to build treatment configs from")
    ap.add_argument("--suffix", default="S1e4_E10x_dt6h",
                    help="Filename suffix: configs/params_treat_<proto>_<suffix>.json")
    ap.add_argument("--out-dir", default="configs")
    ap.add_argument("--gem-dose", type=float, default=None,
                    help="Override gem_dose (paper-calibrated ~0.1; old value 0.4 "
                         "over-kills the tumor — see dose diagnosis)")
    ap.add_argument("--abr-dose", type=float, default=None,
                    help="Override abr_dose (paper-calibrated ~0.015; old value 0.1 over-kills)")
    ap.add_argument("--viz-diffusion", action="store_true",
                    help="Enable the drug-diffusion ParaView visualization "
                         "(sets viz_drug_diffusion=true) in the generated configs. "
                         "Visual only — kill dynamics still use the well-mixed scalar.")
    args = ap.parse_args()

    if args.gem_dose is not None:
        DRUG_BLOCK["gem_dose"] = args.gem_dose
    if args.abr_dose is not None:
        DRUG_BLOCK["abr_dose"] = args.abr_dose

    base_path = (REPO_ROOT / args.base) if not Path(args.base).is_absolute() else Path(args.base)
    base = json.load(open(base_path))
    out_dir = (REPO_ROOT / args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Base template: {base_path.name}  "
          f"(dt={base.get('dt_minutes')}min  E0={base.get('E0')})")
    for proto, spec in PROTOCOLS.items():
        cfg = build_config(base, proto, spec)
        if args.viz_diffusion:
            cfg["viz_drug_diffusion"] = True
        if proto == "untreated":
            fname = f"params_untreated_{args.suffix}.json"
        else:
            fname = f"params_treat_{proto}_{args.suffix}.json"
        path = out_dir / fname
        with open(path, "w") as f:
            json.dump(cfg, f, indent=2)
        flags = [k for k in ("treat_gem", "treat_abr", "treat_acd47") if cfg.get(k)]
        csc = " +CSC" if cfg.get("csc_enable") else ""
        print(f"  {proto:11s} -> {fname}   ({','.join(flags) or 'none'}{csc})")

    print("\nDone.")


if __name__ == "__main__":
    main()
