#!/usr/bin/env python3
"""
run_treatment_production.py — submit treatment protocols in the same per-seed
"production" style as the base runs (one SLURM job per protocol per seed).

Mirrors scripts/run_sensitivity_e10x.py, but each job runs a self-contained
treatment config (generated by make_treatment_configs.py) via
scripts/hpc/job_treatment_prod.sh -> run_direct.sh --config-file. Output is
archived per seed (populations.csv, params.json, treatment ODE reference,
plots, run_info.json) exactly like a base per-seed run.

Layout:
    runs/treatment_prod/<TIMESTAMP>_<suffix>/
        <protocol>/<TIMESTAMP>_<protocol>_s<seed>/...
        suite_manifest.json
        jobs.json

Examples:
    # Smoke test: 1 seed, all protocols
    python3 scripts/run_treatment_production.py --num-seeds 1

    # Full production: 100 seeds, the 4 Fig-5 protocols only
    python3 scripts/run_treatment_production.py --num-seeds 100 \
        --protocols acd47,gem,abr,abr_acd47

    # Dry run (create dirs + configs, print sbatch commands, don't submit)
    python3 scripts/run_treatment_production.py --num-seeds 5 --skip-submit
"""
import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# CSC relapse "abr_csc" (Section 6) DISABLED — this model is Section 5 only.
ALL_PROTOCOLS = ["untreated", "acd47", "gem", "abr", "abr_acd47"]  # , "abr_csc"


def config_for(proto: str, suffix: str) -> Path:
    """Resolve the self-contained config file for a protocol."""
    if proto == "untreated":
        return REPO_ROOT / "configs" / f"params_untreated_{suffix}.json"
    return REPO_ROOT / "configs" / f"params_treat_{proto}_{suffix}.json"


def submit_one(proto, seed, cfg, suite_dir, time_limit, mem, partition, cpus, skip_submit):
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = suite_dir / proto / f"{ts}_{proto}_s{seed}"
    run_dir.mkdir(parents=True, exist_ok=True)

    note = f"treatment-prod {proto} seed={seed}"
    env_ext = (f"ALL,REPO_ROOT={REPO_ROOT},CONFIG={cfg},"
               f"OUTPUT_DIR={run_dir},SEED={seed},SKIP_BUILD=true,NOTE={note}")
    cmd = [
        "sbatch",
        f"--partition={partition}",
        f"--mem={mem}",
        f"--time={time_limit}",
        f"--cpus-per-task={cpus}",
        "--job-name", f"bdm-{proto}-s{seed}",
        "--export", env_ext,
        "scripts/hpc/job_treatment_prod.sh",
    ]

    if skip_submit:
        print(f"  [dry-run] {proto:11s} s{seed:<4d} -> {run_dir.relative_to(REPO_ROOT)}")
        return None, run_dir

    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            universal_newlines=True, cwd=str(REPO_ROOT))
    if result.returncode != 0:
        print(f"  ERROR submitting {proto} s{seed}: {result.stderr.strip()}")
        return None, run_dir
    job_id = result.stdout.strip().split()[-1]
    print(f"  {proto:11s} s{seed:<4d}: job {job_id} -> {run_dir.relative_to(REPO_ROOT)}")
    return job_id, run_dir


def main():
    ap = argparse.ArgumentParser(description="Submit treatment protocols, per-seed production style")
    ap.add_argument("--num-seeds", type=int, default=1,
                    help="Number of seeds per protocol (configurable; default 1)")
    ap.add_argument("--seed-start", type=int, default=1, help="First seed number")
    ap.add_argument("--protocols", default=",".join(ALL_PROTOCOLS),
                    help=f"Comma list. Available: {','.join(ALL_PROTOCOLS)}")
    ap.add_argument("--suffix", default="S1e4_E10x_dt6h",
                    help="Config suffix -> configs/params_treat_<proto>_<suffix>.json")
    ap.add_argument("--output-base", default="runs/treatment_prod")
    ap.add_argument("--time", default="04:00:00", help="SLURM --time per job")
    ap.add_argument("--mem", default="32G", help="SLURM --mem per job (bump for S=1e3)")
    ap.add_argument("--partition", default="cpu",
                    help="SLURM partition (cpu=2d, longcpu=4d, cpu-sb=10d)")
    ap.add_argument("--cpus", type=int, default=16,
                    help="SLURM --cpus-per-task (=OMP threads). Bump for heavy S=1e3.")
    ap.add_argument("--skip-submit", action="store_true",
                    help="Create dirs and print sbatch commands, but don't submit")
    args = ap.parse_args()

    protocols = [p.strip() for p in args.protocols.split(",") if p.strip()]
    bad = [p for p in protocols if p not in ALL_PROTOCOLS]
    if bad:
        print(f"ERROR: unknown protocol(s): {bad}\n       available: {ALL_PROTOCOLS}")
        return 1

    # Verify all configs exist (fail fast before submitting anything)
    missing = [str(config_for(p, args.suffix).relative_to(REPO_ROOT))
               for p in protocols if not config_for(p, args.suffix).exists()]
    if missing:
        print("ERROR: missing config file(s):")
        for m in missing:
            print(f"  {m}")
        print("\nGenerate them first:\n  python3 scripts/make_treatment_configs.py "
              f"--suffix {args.suffix}")
        return 1

    seeds = [args.seed_start + i for i in range(args.num_seeds)]
    suite_name = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{args.suffix}"
    suite_dir = REPO_ROOT / args.output_base / suite_name
    suite_dir.mkdir(parents=True, exist_ok=True)

    total = len(protocols) * len(seeds)
    print("=" * 64)
    print("  Treatment Production Suite")
    print(f"  Suite:     {suite_dir.relative_to(REPO_ROOT)}")
    print(f"  Protocols: {protocols}")
    print(f"  Seeds:     {len(seeds)}  ({seeds[0]}..{seeds[-1]})")
    print(f"  Total jobs:{total}")
    print(f"  Config:    params_*_{args.suffix}.json")
    print("=" * 64)

    jobs = {}
    for proto in protocols:
        cfg = config_for(proto, args.suffix)
        for seed in seeds:
            job_id, run_dir = submit_one(proto, seed, cfg, suite_dir,
                                         args.time, args.mem, args.partition,
                                         args.cpus, args.skip_submit)
            jobs[f"{proto}_s{seed}"] = {
                "job_id": job_id,
                "run_dir": str(run_dir.relative_to(REPO_ROOT)),
                "protocol": proto,
                "seed": seed,
            }

    # Persist manifest + job tracking for post-processing / aggregation
    manifest = {
        "suite": str(suite_dir.relative_to(REPO_ROOT)),
        "timestamp": datetime.now().isoformat(),
        "protocols": protocols,
        "seeds": seeds,
        "suffix": args.suffix,
        "submitted": not args.skip_submit,
    }
    with open(suite_dir / "suite_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
    with open(suite_dir / "jobs.json", "w") as f:
        json.dump(jobs, f, indent=2)

    n_ok = sum(1 for j in jobs.values() if j["job_id"])
    print("-" * 64)
    if args.skip_submit:
        print(f"Dry run: prepared {total} run dirs (nothing submitted).")
    else:
        print(f"Submitted {n_ok}/{total} jobs.")
        print(f"Monitor: squeue -u $USER | grep bdm-")
    print(f"Manifest: {(suite_dir / 'suite_manifest.json').relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
